[project]
name = "item-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.34.2",
]

[tool.ruff.lint]
select = [
    "ANN","FAST","ASYNC","B","A",
    "EXE","ISC","T20","Q","RET",
    "SIM","TID","ARG","C90","N",
    "E","W","F","S",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.0",
]
